# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(default='AddName', max_length=60),
        ),
    ]
