# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-19 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180419_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level_Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.IntegerField(blank=True)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('age', models.IntegerField(blank=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Level_Trainer')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.AlterField(
            model_name='location',
            name='state_province',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='training',
            name='riders',
            field=models.ManyToManyField(blank=True, to='home.Rider'),
        ),
        migrations.AddField(
            model_name='training',
            name='trainers',
            field=models.ManyToManyField(blank=True, to='home.Trainer'),
        ),
    ]
