# Generated by Django 2.0.4 on 2018-04-19 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180419_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Training_program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('warm_up', models.CharField(blank=True, max_length=200)),
                ('core', models.CharField(blank=True, max_length=1000)),
                ('cool_down', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='training',
            name='day',
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='training',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start Time'),
        ),
        migrations.AddField(
            model_name='training',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Training_program'),
        ),
    ]
