# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Type_event'),
        ),
    ]
