# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180614_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cool_down',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_1',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_2',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='warm_up',
            name='content',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
