# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-14 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180614_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='cool_down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Cool_down'),
        ),
        migrations.AddField(
            model_name='training',
            name='core',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Core'),
        ),
        migrations.AddField(
            model_name='training',
            name='warm_up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Warm_up'),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_1_repeat',
            field=models.IntegerField(default=1, verbose_name='aantal keer'),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_2_repeat',
            field=models.IntegerField(default=1, verbose_name='aantal keer'),
        ),
    ]
