# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cool_down',
            name='content_repeat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_1_repeat',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='aantal keer'),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_2',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='core',
            name='content_2_repeat',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='aantal keer'),
        ),
        migrations.AlterField(
            model_name='warm_up',
            name='content_repeat',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
