# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20180618_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cool_down',
            name='name',
            field=models.CharField(default='cooldown', max_length=50),
        ),
        migrations.AlterField(
            model_name='core',
            name='name',
            field=models.CharField(default='core', max_length=50),
        ),
        migrations.AlterField(
            model_name='warm_up',
            name='name',
            field=models.CharField(default='warmup', max_length=50),
        ),
    ]
