# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180618_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rider',
        ),
        migrations.AlterField(
            model_name='training',
            name='riders',
            field=models.ManyToManyField(blank=True, related_name='athlete', to='home.Profile'),
        ),
        migrations.AlterField(
            model_name='training',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trainer', to='home.Profile'),
        ),
    ]
