# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-19 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20180619_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='even_id',
            new_name='event_id',
        ),
    ]
